### ISSUE TITLE
Incorrect changelog since 10.0.2

### ISSUE THREAD

**Issue by CedricDuffournetInfomaniak** [release-it/conventional-changelog#128]
Since v10.0.2 change log is incorrect

here is my configuration

```json
{
  "git": {
    "requireBranch": "master",
    "commitMessage": "chore(release): ${version}",
    "tagExclude": "*[-]*"
  },
  "npm": {
    "publish": false
  },
  "plugins": {
    "@release-it/conventional-changelog": {
      "infile": "CHANGELOG.md",
      "preset": {
        "name": "conventionalcommits",
        "types": [
          {
            "type": "feat",
            "section": "🎉 Features"
          },
          {
            "type": "fix",
            "section": "🐛 Bug Fixes"
          },
          {
            "type": "chore",
            "section": "⚙️ Chore"
          },
          {
            "type": "docs",
            "section": "📚 Documentation"
          },
          {
            "type": "style",
            "section": "🎨 Code style"
          },
          {
            "type": "refactor",
            "section": "🚜 Refactor"
          },
          {
            "type": "perf",
            "section": "⚡ Performance"
          },
          {
            "type": "test",
            "section": "🧪 Test"
          },
          {
            "type": "ci",
            "section": "🤖 Continuous Integration"
          },
          {
            "type": "build",
            "section": "📦️ Build"
          }
        ]
      }
    }
  }
}
```

## the output on 10.0.1

```terminal
> release-it --dry-run

$ git rev-parse --abbrev-ref HEAD
$ git diff --quiet HEAD
$ git rev-parse --abbrev-ref HEAD  [cached]
$ git config --get branch.master.remote
$ git remote get-url origin
! git fetch
$ git rev-parse --abbrev-ref HEAD  [cached]
$ git describe --tags --match=* --abbrev=0 --exclude=*[-]*
$ git symbolic-ref HEAD
$ git for-each-ref --format="%(upstream:short)" refs/heads/master

🚀 Let's release site-manager-hosting (6.0.0...6.0.1)


Changelog:
## [6.0.1](https://xxx/site-manager-hosting/compare/6.0.0...6.0.1) (2025-11-24)
### ⚙️ Chore
* **angular:** migration to angular 21 ([d56930e](https://xxx/site-manager-hosting/commit/d56930e06ac35b1e487d4cca0eaf96dff57679eb))

! npm version 6.0.1 --no-git-tag-version
$ Writing changelog to CHANGELOG.md
$ git status --short --untracked-files=no
```

## the output on 10.0.2

```terminal
> release-it --dry-run

$ git rev-parse --abbrev-ref HEAD
$ git diff --quiet HEAD
$ git rev-parse --abbrev-ref HEAD  [cached]
$ git config --get branch.master.remote
$ git remote get-url origin
! git fetch
$ git rev-parse --abbrev-ref HEAD  [cached]
$ git describe --tags --match=* --abbrev=0 --exclude=*[-]*
$ git symbolic-ref HEAD
$ git for-each-ref --format="%(upstream:short)" refs/heads/master

🚀 Let's release site-manager-hosting (6.0.0...6.0.1)


Changelog:
## [6.0.1](///compare/6.0.0...6.0.1) (2025-11-24)

! npm version 6.0.1 --no-git-tag-version
$ Writing changelog to CHANGELOG.md
$ git status --short --untracked-files=no

Empty changeset

! git add . --update
```

Do i need to update my configuration in v10.0.2 ?

**Comment by robertsLando** [comment]
@webpro Having this issue as well

**Comment by jeffnyman** [comment]
I'm finding problems even in 10.0.1. Here is my config:

```
{
  "$schema": "https://unpkg.com/release-it@19/schema/release-it.json",
  "npm": {
    "publish": false
  },
  "git": {
    "requireBranch": "main",
    "commitMessage": "chore: release v${version}",
    "commit": true,
    "tag": true,
    "push": true
  },
  "github": {
    "web": true,
    "release": true,
    "releaseName": "Release ${version}"
  },
  "hooks": {
    "before-init": "npm run build"
  },
  "plugins": {
    "@release-it/conventional-changelog": {
      "infile": "CHANGELOG.md",
      "preset": {
        "name": "conventionalcommits",
        "types": [
          {
            "type": "feat",
            "section": "Features"
          },
          {
            "type": "fix",
            "section": "Bug Fixes"
          },
          {}
        ]
      }
    }
  }
}
```

When I generate a dry-run, I get every commit. Example from output:

```
- chore: update repo configuration ([bcd78de](https://xxx/improbable-mission-canonical/commit/bcd78de))
- feat: add browser capability checking with user feedback ([213e459](https://xxx/improbable-mission-canonical/commit/213e459))
- feat: add toolbar interface ([7de4c54](https://xxx/improbable-mission-canonical/commit/7de4c54))
- feat: add user interactable section to start the game ([ebbca0c](https://xxx/improbable-mission-canonical/commit/ebbca0c))
- refactor: avoid flash of unstyled content on startup ([6fdb325](https://xxx/improbable-mission-canonical/commit/6fdb325))
- refactor: modularize styles ([f21d948](https://xxx/improbable-mission-canonical/commit/f21d948))
- Add build configuration. ([c766d10](https://xxx/improbable-mission-canonical/commit/c766d10))
```

I would expect, based on my configuration, to only see feat or fix. Unless I'm misunderstanding how to configure this, which is quite possible. I do agree that the compare links are entirely broken in 10.0.2 and up.

**Comment by CedricDuffournetInfomaniak** [comment]
@Maxel01 no dit not have time yet, but thank you for the PR

**Comment by Maxel01** [comment]
@CedricDuffournetInfomaniak 
Can you confirm that this issue has been completely solved with version 10.0.4?

**Comment by SahilAggarwal2004** [comment]
> > [@CedricDuffournetInfomaniak](https://github.com/CedricDuffournetInfomaniak) Can you confirm that this issue has been completely solved with version 10.0.4?
> 
> It's not

Well, I recently updated to version 10.0.4, and its worked perfectly fine for me.

**Comment by Nicolas-PredictaLab** [comment]
> > > > Might be different. Yesterday I was having the same issue as [@CedricDuffournetInfomaniak](https://github.com/CedricDuffournetInfomaniak) : chore wasn't rendered in Changelog. Now I have this problem : [#104](https://github.com/release-it/conventional-changelog/issues/104)
> > > 
> > > 
> > > Please check your messages. This helps nobody. Linking to an issue not related to this problem is not helpful.
> > 
> > 
> > Please read my message.
> > When I say yesterday "It's not" it's because it's not. In latest release, chore commits are not rendered in changelog.
> 
> Please read my message. Linking to issue 104 is not helpful for your new problem when you say 'I have this problem now'. 104 claims that the maintainer needs help to maintain this repo.

Ok sorry don't have more time to spend trying to make you understand that issue mentioned in THIS thread is still here, as you asked me yesterday. Bye.

**Comment by CedricDuffournetInfomaniak** [comment]
@Maxel01 this is working perfectly for me, thank you for the fix !

**Comment by SahilAggarwal2004** [comment]
Hi @Maxel01 @webpro,
Idk what's happening, but this issue still occurs occasionally (randomly, for no reason). And gets fixed itself after some time.
Am I the only one facing this problem?

**Comment by SahilAggarwal2004** [comment]
Got it why it felt so random.

So when I run it directly as:
```
release-it --ci --dry-run
```
It doesn't pickup the git repo correctly for some reason.

And when I run it as:
```
pnpm run dry-release
```

with:
```
"scripts": {
  "build": "pnpm i && pnpm run compile",
  "compile": "tsup",
  "dev": "tsup --watch",
  "dry-release": "release-it --ci --dry-run",
  "prettier": "prettier-package-json --write package.json",
  "pub": "pnpm login && pnpm publish",
  "release": "release-it --ci"
}
```
It just works

**Comment by SahilAggarwal2004** [comment]
Nvm, my global installations of release-it and @release-it/conventional-changelog (v10.0.2) were outdated 😭
